# Generated by Django 3.1.4 on 2020-12-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='view',
            field=models.TextField(default=False),
        ),
    ]
