# Generated by Django 3.1.4 on 2020-12-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdj', '0002_customers_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='view',
            field=models.TextField(),
        ),
    ]
